"""globals - 全局函数

从 runner.py 导出聚宽风格全局函数
"""

# 这些函数在 runner.py 中定义，通过 engine 包导入
from jk2bt.engine.runner import (
    order,
    order_value,
    order_target_value,
    order_target,
    run_daily,
    run_weekly,
    run_monthly,
    unschedule_all,
    set_option,
    set_benchmark,
    set_slippage,
    set_order_cost,
    set_universe,
    set_subportfolios,
    get_trades,
    get_locked_shares,
    get_dominant_future,
    get_future_contracts,
    g,
    log,
    FixedSlippage,
    OrderCost,
    LimitOrderStyle,
    MarketOrderStyle,
    PriceRelatedSlippage,
    StepRelatedSlippage,
    SubPortfolioConfig,
    OrderStatus,
    PerTrade,
    disable_cache,
    set_commission,
)

__all__ = [
    "order",
    "order_value",
    "order_target_value",
    "order_target",
    "run_daily",
    "run_weekly",
    "run_monthly",
    "unschedule_all",
    "set_option",
    "set_benchmark",
    "set_slippage",
    "set_order_cost",
    "set_universe",
    "set_subportfolios",
    "get_trades",
    "get_locked_shares",
    "get_dominant_future",
    "get_future_contracts",
    "g",
    "log",
    "FixedSlippage",
    "OrderCost",
    "LimitOrderStyle",
    "MarketOrderStyle",
    "PriceRelatedSlippage",
    "StepRelatedSlippage",
    "SubPortfolioConfig",
    "OrderStatus",
    "PerTrade",
    "disable_cache",
    "set_commission",
]
